### ISSUE TITLE
Problem with modal

### ISSUE THREAD

**Issue by raoulalobo** [coderhaoxin/react-flatpickr#25] opened 2017-04-25 10:21 UTC
Hi , when i use react modal with react-flatpickr year and month dont work fine. 
Sorrty for my poor english

**Comment by jacobmischka** [comment] 2017-04-25 12:04
Sorry, can you provide any more information?

**Comment by raoulalobo** [comment] 2017-04-25 12:37
![image](https://cloud.githubusercontent.com/assets/12596224/25385019/6c3ab1c6-29ba-11e7-8a82-54c9106aaeeb.png)
When i want to change month it doesnt work, for exemple when i want to go to the next month there is superpostion

**Comment by jacobmischka** [comment] 2017-04-25 13:05
What are you using to create the modals?

**Comment by raoulalobo** [comment] 2017-04-25 14:33
"react-modal": "^1.6.5",

**Comment by jacobmischka** [comment] 2017-04-25 15:52
Can you try running `npm upgrade`? Flatpickr (the original library, not this package) had an update a couple of days ago that fixed some `destroy()` problems it looks like. After doing that I don't seem to have any issues using react-flatpickr in a modal. If you can give me some code that reproduces the problem I'd be more than happy to take a look.

**Comment by jacobmischka** [comment] 2017-05-05 04:47
Closing for now because I can't reproduce after updating like I mentioned, feel free to write back if you're still experiencing this.

**Closed by jacobmischka** 2017-05-05 04:47 UTC

**Comment by JosueDevMark** [comment] 2018-02-26 18:14
Hi @jacobmischka, this is a Flatpickr bug, so is resolver at the latest version, I have made a [PR](https://github.com/coderhaoxin/react-flatpickr/pull/63) to resolve it (just upgrade the dependency version). If you can review it could be great
