### ISSUE TITLE
onChanged doesn't fire on changing times

### ISSUE THREAD

**Issue by kurt-o-sys** [coderhaoxin/react-flatpickr#72] opened 2018-09-06 04:52 UTC
`onChange` is not triggered after time input value update. This is an old issue in `Flatpickr`: https://github.com/flatpickr/flatpickr/issues/1166

`react-flatpickr` uses an old version of `flatpickr`. From `package.json`:
```
    "flatpickr": "^4.3.2",
```
The last version of `flatpickr is `v4.5.2`.

Updating this dependency may solve this.

**Comment by jacobmischka** [comment] 2018-09-06 12:11
The `^` means that it will use the most recent `4` version, running `npm upgrade` or `rm -r node_modules && npm install` should install the newest version of flatpickr for you.

Please write back if you find that's not the case.

**Comment by kurt-o-sys** [comment] 2018-09-09 07:49
Right... so it seems to use version 4.5.2. So the problem seems to be something else. It still exists: `onChange` is not triggered when updating the time input value.

**Comment by kurt-o-sys** [comment] 2018-09-15 18:51
any idea why `onChange` is not called when changing the time... It does change when changing the date, though.

**Comment by kurt-o-sys** [comment] 2018-09-20 09:36
some code:

```
<Flatpickr options={{enableTime:  true,
                     time_24hr:   true,
                     formatDate:  function(date) {...},
                     weekNumbers: true}}
           value={value}
           onChange=function(selectedDates, dateStr, instance) {...} />
```

So, whenever I change the time, `onChange` is not triggered. When I change the date, date and time are updated appropriately.

**Comment by jacobmischka** [comment] 2018-09-20 10:17
Sorry, unsure what to tell you, I can't seem to reproduce. It might be an issue with your `formatDate` function, I'm not entirely sure how that interacts under the hood.

![peek 2018-09-20 05-12](https://user-images.githubusercontent.com/3939997/45812111-7b066b00-bc94-11e8-9c57-cd126649ed23.gif)

**Comment by jacobmischka** [comment] 2018-10-13 15:58
Closing because I can't reproduce, feel free to write back with some more info and I can reopen.

**Closed by jacobmischka** 2018-10-13 15:58 UTC

**Comment by iranana** [comment] 2018-10-15 01:18
I don't know if this intended behaviour, but I ran into a case of onChange not firing, which may be related to OPs issue.

If you don't display the time, then the onChange event doesn't fire when changing times (only when changing dates, or AM/PM). This is a non-issue for me I will always display times when the time picker is enabled.

https://codepen.io/anon/pen/OBxrmv?editors=1111
