### ISSUE TITLE
The picker does not work during server side rendering.

### ISSUE THREAD

**Issue by iarvind** [coderhaoxin/react-flatpickr#9] opened 2016-12-13 15:17 UTC
I see this error during startup of my server.
ReferenceError: document is not defined
    at Object.<anonymous> (/node_modules/flatpickr/dist/flatpickr.js:1571:22)

 **Is there a way where I don't have to do check for `(typeof window !== 'undefined')`**

**Comment by coderhaoxin** [comment] 2016-12-14 01:55
Can you give me a code snippet to reproduce this? (I don't use server side rendering personally ((^_^))!!~~)

**Comment by snobojohan** [comment] 2017-01-26 09:56
In a project that has server rendering I use it only in browser, since we only show it after users have clicked. What we do is check if we are in the browser when importing.

```
import {isBrowser} from '../../utils/environment';
const Flatpickr = isBrowser() ? require('react-flatpickr') : () => false;
```

So now when using `<Flatpickr />` it's nothing when server rendering. The `isBrowser()` function is very simple.

```
export function isBrowser() {
    return typeof window === 'object';
}
```

**Comment by nfriedly** [comment] 2017-08-08 19:20
This is now fixed in flatpickr v3.0.7; I just sent #40 to update react-flatpickr to the latest release.

**Closed** 2017-08-09 02:09 UTC
Labels: help wanted, question

**Comment by redbmk** [comment] 2017-10-12 21:43
There seems to have been some regression here. I think it's due, at least in part, to these two lines:

`window.flatpickr = flatpick` ([`index.ts`](https://github.com/chmln/flatpickr/blob/cfedaee72eb8d364f6fa24648165005a760dc312/src/index.ts#L2602))

`animate: window && window.navigator.userAgent.indexOf("MSIE") === -1,` ([`types/options.ts`](https://github.com/chmln/flatpickr/blob/cfedaee72eb8d364f6fa24648165005a760dc312/src/types/options.ts#L285))
